name: Codeberg Mirror

on: [push]

jobs:
  codeberg-mirror:
    name: Codeberg Mirror
    runs-on: ubuntu-latest
    steps:
      - uses: yesolutions/mirror-action@master
        with:
          REMOTE: 'https://codeberg.org/OverEngineer/cuteInjector'
          GIT_USERNAME: 'OverEngineer'
          GIT_PASSWORD: ${{ secrets.CODEBERG_TOKEN }}
